# Generated by Django 4.2.7 on 2026-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.BinaryField()),
                ('adjusted_image', models.BinaryField()),
                ('person_number', models.CharField(max_length=50)),
                ('adjust_reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_number', models.CharField(db_index=True, max_length=50)),
                ('photo_blob', models.BinaryField()),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('adjust_details', models.JSONField(default=dict)),
                ('status', models.CharField(default='confirmed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
    ]
