# Generated by Django 4.2.7 on 2026-04-05 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_upload_validation_and_quality_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingconfirmation',
            options={'ordering': ('-created_at',), 'verbose_name': '待确认照片', 'verbose_name_plural': '待确认照片'},
        ),
        migrations.AlterModelOptions(
            name='personphoto',
            options={'ordering': ('-upload_time',), 'verbose_name': '人员照片', 'verbose_name_plural': '人员照片'},
        ),
        migrations.AlterModelOptions(
            name='uploadbatch',
            options={'ordering': ('-start_time',), 'verbose_name': '上传批次', 'verbose_name_plural': '上传批次'},
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='adjust_reason',
            field=models.CharField(max_length=200, verbose_name='调整原因'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='adjusted_image',
            field=models.BinaryField(verbose_name='调整后图像'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='original_image',
            field=models.BinaryField(verbose_name='原图'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='person_number',
            field=models.CharField(max_length=50, verbose_name='人员编号'),
        ),
        migrations.AlterField(
            model_name='pendingconfirmation',
            name='upload_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.uploadbatch', verbose_name='上传批次'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='adjust_details',
            field=models.JSONField(default=dict, verbose_name='调整详情'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.uploadbatch', verbose_name='上传批次'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='is_adjusted',
            field=models.BooleanField(default=False, verbose_name='是否经自动调整'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='person_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='人员编号'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='photo_blob',
            field=models.BinaryField(verbose_name='照片数据'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='人脸相似度'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='status',
            field=models.CharField(default='confirmed', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='fail_count',
            field=models.IntegerField(default=0, verbose_name='失败数量'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='最后错误信息'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='max_retries',
            field=models.IntegerField(default=3, verbose_name='最大重试次数'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(default='processing', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='成功数量'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='total_count',
            field=models.IntegerField(default=0, verbose_name='总数量'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='uploadvalidationconfig',
            name='background_color_rules',
            field=models.JSONField(default=list, help_text='与 settings 中 BACKGROUND_ALLOWED_COLORS 相同结构，例如 [{"r_min":200,"r_max":255,"g_min":200,"g_max":255,"b_min":200,"b_max":255}]', verbose_name='背景色规则'),
        ),
    ]
