# Generated by Django 4.2.7 on 2026-04-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_zh_upload_person_pending_verbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='OraclePhotoSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用 Oracle 同步')),
                ('uploader_must_opt_in', models.BooleanField(default=True, help_text='勾选：上传页显示选项，仅勾选时写入。取消勾选：每次本系统入库成功后自动写入 Oracle。', verbose_name='上传时需手动勾选才写入 Oracle')),
                ('default_opt_in_checked', models.BooleanField(default=False, verbose_name='上传页选项默认勾选')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=1521, verbose_name='端口')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='服务名 / Service Name')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=256, verbose_name='密码')),
                ('table_schema', models.CharField(blank=True, help_text='可空，表示使用连接用户的默认方案。', max_length=128, verbose_name='表所在 Schema（可空）')),
                ('table_name', models.CharField(blank=True, max_length=128, verbose_name='表名')),
                ('person_key_column', models.CharField(blank=True, help_text='与上传文件名中人员编号对应的列（如学号、证件号），用于 WHERE 条件。', max_length=128, verbose_name='人员键字段名')),
                ('photo_blob_column', models.CharField(blank=True, help_text='写入照片二进制数据的列（BLOB 或 RAW 等可接受二进制类型）。', max_length=128, verbose_name='照片 BLOB 字段名')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oracle 照片同步配置',
                'verbose_name_plural': 'Oracle 照片同步配置',
            },
        ),
    ]
