# Generated by Django 4.2.7 on 2026-04-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_oracle_photo_sync_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraclephotosyncconfig',
            name='password',
            field=models.CharField(blank=True, help_text='以 Fernet 密文保存；生产环境请设置环境变量 ORACLE_SYNC_FERNET_KEY（python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"）。未设置时由 Django SECRET_KEY 派生。', max_length=512, verbose_name='密码（加密存储）'),
        ),
    ]
