# Generated by Django 4.2.7 on 2026-04-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_encrypt_legacy_oracle_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperuserCryptoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_sync_fernet_key', models.CharField(blank=True, default='', help_text='用于解密 Oracle 同步配置中的数据库密码；留空则使用 Django SECRET_KEY 派生密钥。', max_length=128, verbose_name='Oracle Fernet 密钥')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '超级管理员密钥配置',
                'verbose_name_plural': '超级管理员密钥配置',
            },
        ),
    ]
