# Generated by Django 4.2.7 on 2026-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': '系统配置项', 'verbose_name_plural': '系统配置项'},
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.CharField(max_length=500, verbose_name='配置值'),
        ),
    ]
